title: EWRL
description: On this site you will find all information about the European Workshop on Reinforcement Learning (EWRL) series!
theme: just-the-docs

url: https://github.com/ewrl-org/ewrl

aux_links:
  Github Repository: https://github.com/ewrl-org/ewrl
